### ISSUE TITLE
trans UIView to MTKView failed

### ISSUE THREAD

**Issue by Knni9ht** [Waley-Z/ios-depth-point-cloud#3]
when i run this code in my mac,i met error;while the code excuted to "if let view = view? MTKView",it failed; and i print the view which showed it's a UIView,not MTKVIew;so the code didnot excute into the if sentence.
i wonder is there anything i should do before run the code

**Comment by Waley-Z** [comment]
Hi, have you tried running the [original](https://github.com/Waley-Z/ios-depth-point-cloud/tree/original) code given by Apple?

**Comment by Knni9ht** [comment]
> Hi, have you tried running the [original](https://github.com/Waley-Z/ios-depth-point-cloud/tree/original) code given by Apple?

yes，i tried. And I have fixed this porblem by the following codes:
    override func loadView() {
        self.view = MTKView()
    }
